# Generated by Django 3.2.9 on 2022-05-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='Age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='register',
            name='Name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='Password',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='Photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='Place',
            field=models.CharField(default='', max_length=10),
        ),
    ]
